### ISSUE TITLE
What is the roadmap here?

### ISSUE THREAD

**Issue by eaydin-dev** [inteoryx/StumblingOnUI#1]
I would like to contribute to this project, especially on frontend. Are there any plans or a roadmap?

**Comment by inteoryx** [comment]
Thanks.  Roadmap is pretty wide open and unofficial.  If you have ideas for the project I'd love to hear them.  You can send me an email with thoughts at inteoryx at protonmail dot com.  I put up a rough outline on the wiki - https://github.com/inteoryx/StumblingOnUI/wiki
